# Generated by Django 3.1.6 on 2021-04-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_token", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expiringtoken",
            name="ip_addr",
            field=models.GenericIPAddressField(default=None, null=True),
        ),
    ]
