# Generated by Django 3.1.6 on 2021-07-26 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_token', '0002_expiringtoken_ip_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiringtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
