# Generated by Django 3.1.6 on 2021-07-28 18:51

import api.auth_token.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth_token', '0003_auto_20210726_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expiringtoken',
            name='expires',
        ),
        migrations.RemoveField(
            model_name='expiringtoken',
            name='key',
        ),
        migrations.RemoveField(
            model_name='expiringtoken',
            name='valid_until',
        ),
        migrations.AddField(
            model_name='expiringtoken',
            name='refresh_token',
            field=models.CharField(default=api.auth_token.models.generate_key, max_length=1024),
        ),
        migrations.AddField(
            model_name='expiringtoken',
            name='refresh_token_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 28, 18, 51, 18, 34053, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='expiringtoken',
            name='refresh_token_valid_until',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 28, 18, 51, 18, 34053, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='expiringtoken',
            name='token',
            field=models.CharField(default=api.auth_token.models.generate_key, max_length=1024, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='expiringtoken',
            name='token_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 28, 18, 51, 18, 34053, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='expiringtoken',
            name='token_valid_until',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 28, 18, 51, 18, 34053, tzinfo=utc)),
        ),
    ]
