# Generated by Django 3.2 on 2021-09-25 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_token", "0008_auto_20210805_2031"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExpiringToken",
        ),
    ]
